export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const PURCHASE_CONTINUED = 'PURCHASE_CONTINUED';
export const PURCHASE_CANCELED = 'PURCHASE_CANCELED';
export const PURCHASE_STARTED = 'PURCHASE_STARTED';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_CONTINUED = 'FETCH_ORDERS_CONTINUED';
export const FETCH_ORDERS_CANCELED = 'FETCH_ORDERS_CANCELED';
export const FETCH_ORDERS_STARTED = 'FETCH_ORDERS_STARTED';
export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';






export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CANCELED = 'AUTH_CANCELED';
export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_CHANGE_PATH = 'AUTH_CHANGE_PATH';

